language: node_js

node_js:
- node

script:
- yarn build
- yarn test

deploy:
  provider: npm
  skip_cleanup: true
  email:
    secure: KSOI7ryIx1cgkBWPUcJVddtMfD2haN1Dg/9g6SiTuxAUEtUXP8Buq5JiG+sunuspHTtqZi5LAzy7+AVwR6/i7uRj+VXVr+UhZyZZlqAuaw7Gwe4IRDSvEbfIRSjyfQ8cW1/2tKAU5EZl0n5u3bjDfZ8Mam6iQ/TjLcjjSgYqKxk1v2Wh4TsyR1Ion4qoANN0lh0J0I3Wjti/7orXguD5TwH+KnqsoNrf4M153TswSk5YruoPcCcZMPY8CHXASnLP19AkKwzNjULmi2H/ESGa/VtSQMxGermHS1xs0rxWGcTjpMPrvaO3k2dVryTK3UhMgQdaBfqFUD62+HYZTEFmTCeb/08y7hqZuqWhYfwcG1xsw6H8Nf43kPUYrl/5TSYiPSD3MjyYCg9NCgm+msoSc9bw1h63Rk8mSbI++tJz3WaKZVmwLPD7kPOUPRRQ5sE2DYe09+wn8PXLyesQ/S+pwEVFKjwZ/ATVbRp7AGxTEq7CbZ0DhBSvPoyBvcoOrqz/u631M6jcWeSxPKJW4Wo0mxlW2UWauTBn3NV2V/RIcHuZHxDXYnf6zPoAHKsKQ+bUd2L614quUk0e7OdQQ6eWy6wsZo6hzNWJUNL8cQFkyJn5TmpBfk2tHZ9nIhN9MhPtb9Pfx0Ur+VDSL/hW+vmyTjwj7oQqyCfYcxGX7AFYARA=
  api_key:
    secure: Ec6XjRWNJTTTplPUxsiUQUHCtIZQivbXaloq+pedL7aDPnAkEC/GtHif8W04Vu5QQkRBu9hXNVQkQGXgFP9LK9Lv6g1okwGE/l6CqahfnW4SjIUUBt+mHcox2fy4m+86x18dQ5lDUtQnEGm+vj0FGJvN4PUhaBUM6tjonkyRcb6SMf5uptWaL7bMz5eUyKbVyHgYcDw9v5cW64icMzFv3oqJzWdZw8ONDuttBxkOg+c2k8STEdQsobZwfXA+ET7P+U1yacYJlSEeqc4+IhOHpadZ0Yw2N5Kz4TdPUnLwjrDUfFYobN6UysvSxRvCicPd24MnTL4LXF+ngm9CzaKBTH6JjTaLUu71oOaP3l4x1k3XoTYUQnigM60X8qmGeec/Gmc/dpweaXS3ZsIs3DGkkr2TqsfJ/kjTgqcrttLClXPuQAvnupoO2D03rpVuUQM9dyRnQ95lTccTTFqVrVA0pE3e0L3PlK5O1yHb94C0m43gFZGFw12VAx6cvkejVoYVB6nprc7W4/4yEnfTSzFtydSOPewQrEMMg32Bvh60No8EeY57ROmKYKERkqdNGMCWotb/IfM536dv6Wi5xWGYN+WTFsBqvpVw2HzJXf52o+uL+FbcFV72/hFGMLsm8GTvcjnBRH4U9y3g+VpiNIXbuEjDMp66a5tdptyivd8ja5g=
  on:
    tags: true
